name: maggie
channels:
- bioconda
- conda-forge
dependencies:
- python=3.9
- numpy
- pandas
- biopython=1.79
- scipy=1.8
- matplotlib
- seaborn
- tqdm
- pip
- pip:
    - requests
    - logomaker==0.8

