name: maggie
channels:
- bioconda
- conda-forge
dependencies:
- python=3.6
- numpy=1.15
- pandas=0.20
- biopython=1.70
- scipy==1.1.0
- matplotlib==2.0.2
- seaborn==0.7.1
- tqdm=4.41.1
- pip=19.2.3
- pip:
    - logomaker==0.7